version: "3.8"
services:
  # Orion is an NGSI-v2 context broker
  orion1:
    image: quay.io/fiware/orion:3.11.0
    hostname: orion1
    container_name: fiware-orion1
    restart: on-failure
    depends_on:
      mongo-db1:
        condition: service_healthy
    expose:
      - "1026"
    ports:
      - "1026:1026"
    networks:
      fiware-network:
        ipv4_address: 172.19.1.2
    command: -dbhost mongo-db1 -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion1:1026/version || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5s

  # MongoDB for Orion
  mongo-db1:
    image: mongo:6.0
    hostname: mongo-db1
    container_name: mongo-db1
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      fiware-network:
        ipv4_address: 172.19.1.3
    volumes:
      - ./data/mongo-db1:/data
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      start_period: 10s
      interval: 10m
      timeout: 5s
      retries: 3

  spark-master:
    image: bitnami/spark:3.5.3
    hostname: spark-master
    container_name: spark-master
    restart: on-failure
    depends_on:
      - orion1
    expose:
      - "4040"
      - "8080"
      - "7077"
      - "9001"
    ports:
      - "4040:4040"
      - "8080:8080"
      - "7077:7077"
      - "9001:9001"
    networks:
      fiware-network:
        ipv4_address: 172.19.1.3
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=0.0.0.0
      - PYSPARK_PYTHON=/usr/bin/python3.12
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark-worker1:
    image: bitnami/spark:3.5.3
    hostname: spark-worker1
    container_name: spark-worker1
    restart: on-failure
    depends_on:
      - spark-master
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      fiware-network:
        ipv4_address: 172.19.1.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=0.0.0.0
      - PYSPARK_PYTHON=/usr/bin/python3.12
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  fiware-network:
    name: fiware-network
    # driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24

volumes:
  mongo-db1:

