version: "3.8"
services:
  # Orion is an NGSI-v2 context broker
  orion1:
    image: quay.io/fiware/orion:3.11.0
    hostname: orion1
    container_name: fiware-orion1
    restart: on-failure
    depends_on:
      mongo-db1:
        condition: service_healthy
    expose:
      - "1026"
    ports:
      - "1026:1026"
    networks:
      - fiware-network
    command: -dbhost mongo-db1 -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion1:1026/version || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5s

  # MongoDB for Orion
  mongo-db1:
    image: mongo:6.0
    hostname: mongo-db1
    container_name: mongo-db1
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - fiware-network
    volumes:
      - ./data/mongo-db1:/data
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      start_period: 10s
      interval: 10m
      timeout: 5s
      retries: 3

  flink-jobmanager:
    image: flink:1.9.0-scala_2.11
    hostname: flink-jobmanager
    container_name: flink-jobmanager
    expose:
        - "8080"
        - "9001"
    ports:
        - "6123:6123"
        - "8081:8081"
    networks:
      - fiware-network
    command: jobmanager
    environment:
        - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

  flink-taskmanager:
    image: flink:1.9.0-scala_2.11
    hostname: flink-taskmanager
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    ports:
      - "6121:6121"
      - "6122:6122"
      - "9001:9001"
    networks:
      - fiware-network
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

networks:
  fiware-network:
    name: fiware-network
    ipam:
      config:
        - subnet: 172.19.1.0/24

volumes:
  mongo-db1:
  cygnus:
  kafka:

