version: "3.8"
services:
  # Orion is an NGSI-v2 context broker
  orion1:
    image: quay.io/fiware/orion:3.11.0
    hostname: orion1
    container_name: fiware-orion1
    depends_on:
      - mongo-db1
    expose:
      - "1026"
    ports:
      - "1026:1026"
    networks:
      - fiware-network
    command: -dbhost mongo-db1 -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion1:1026/version || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5s

  # MongoDB for Orion
  mongo-db1:
    image: mongo:6.0
    hostname: mongo-db1
    container_name: mongo-db1
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - fiware-network
    volumes:
      - mongo-db1:/data
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5s

  # QuantumLeap
  quantumleap:
    image: orchestracities/quantumleap:1.0.0
    labels:
      org.fiware: 'tutorial'
    hostname: quantumleap
    container_name: fiware-quantumleap
    expose:
      - "8668"
    ports:
      - "8668:8668"
    depends_on:
      - timescale
    networks:
      - fiware-network
    environment:
      - QL_DEFAULT_DB=timescale          # バックエンド: timescale また crate
      - POSTGRES_HOST=timescale          # PostgreSQL ホスト
      - POSTGRES_PORT=5432               # PostgreSQL ポート
      - POSTGRES_HOST_AUTH_METHOD=trust  # PostgreSQL 認証なし
      - POSTGRES_USER=quantumleap        # PostgreSQL ルートユーザ
      - POSTGRES_PASSWORD=*              # PostgreSQL ルートユーザのパスワード
      - POSTGRES_DB_NAME=quantumleap     # PostgreSQL デフォルトdb
      - POSTGRES_DB_USER=quantumleap     # PostgreSQL デフォルトdbのユーザ
      - POSTGRES_DB_PASS=*               # PostgreSQL デフォルトdbのパスワード
      - POSTGRES_USE_SSL=False
      - LOGLEVEL=DEBUG
    healthcheck:
      test: curl --fail -s http://quantumleap:8668/version || exit 1

  # Timescale(PostgreSQL) for QuantumLeap
  timescale:
    image: timescale/timescaledb-postgis:2.2.1-pg13
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - fiware-network
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust # PostgreSQL 認証なし
      - POSTGRES_USER=quantumleap       # PostgreSQL ルートユーザ
      - POSTGRES_PASSWORD=*             # PostgreSQL ルートユーザのパスワード
      - TZ=Asia/Tokyo

  # DB Setup for Timescale(PostgreSQL)
  quantumleap-db-setup:
    image: orchestracities/quantumleap-pg-init
    depends_on:
      - timescale
    environment:
      - QL_DB_PASS=*
      - QL_DB_INIT_DIR=/ql-db-init
      - PG_HOST=timescale
      - PG_PASS=*

networks:
  fiware-network:
    name: fiware-network
    ipam:
      config:
        - subnet: 172.19.1.0/24

volumes:
  mongo-db1:
