version: "3.8"
services:
  # Orion is an NGSI-v2 context broker
  orion1:
    image: quay.io/fiware/orion:3.11.0
    hostname: orion1
    container_name: fiware-orion1
    depends_on:
      - mongo-db1
    expose:
      - "1026"
    ports:
      - "1026:1026"
    networks:
      - fiware-network
    command: -dbhost mongo-db1 -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion1:1026/version || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5s

  # MongoDB for Orion
  mongo-db1:
    image: mongo:6.0
    hostname: mongo-db1
    container_name: mongo-db1
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - fiware-network
    volumes:
      - mongo-db1:/data
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5s

  draco:
    image: ging/fiware-draco:2.1.0
    hostname: draco
    container_name: draco
    restart: on-failure
    expose:
      - 8080
    ports:
      - "8080:8080"
      - "9090:9090"
      - "5050:5050"
    networks:
      - fiware-network
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=9090
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin
    volumes:
      - ./draco/database:/opt/nifi-registry/nifi-registry-current/database
      - ./draco/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - ./draco/fileprocessor:/opt/nifi/nifi-current/fileprocessor

networks:
  fiware-network:
    name: fiware-network
    ipam:
      config:
        - subnet: 172.19.1.0/24

volumes:
  mongo-db1:
  draco:
